global using CommunityToolkit.Maui;
global using CommunityToolkit.Maui.Alerts;
global using CommunityToolkit.Maui.Core;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using MauiApp2.Models;
global using MauiApp2.Pages;
global using MauiApp2.Services;
global using MauiApp2.Uuids;
global using MauiApp2.ViewModels;
global using Microsoft.Maui.ApplicationModel;
global using Plugin.BLE;
global using Plugin.BLE.Abstractions;
global using Plugin.BLE.Abstractions.Contracts;
global using Plugin.BLE.Abstractions.EventArgs;
global using System.Collections.ObjectModel;
global using System.Diagnostics;
global using IAdapter = Plugin.BLE.Abstractions.Contracts.IAdapter;
